#!/bin/bash

# lib-sh/common - Common functions for everyday use
# Copyright (c) 2016 by Oleksii Tsvietnov, me@vorakl.name
# Version: v0.1.0

if [ "${__LIB_SH_COMMON__:-empty}" = "empty" ]; then
    export __LIB_SH_COMMON__="imported"
else
    return 0
fi

declare -F __init__ &> /dev/null && __init__ || return 0
